### ISSUE TITLE
Issue with docker-compose with mounted volume and different host from container OS

### ISSUE THREAD

**Issue by ESWAT** [HabitRPG/habitica#10157]
I noticed an issue if I try running habitica with `docker-compose` with these conditions:

1. Local habitica mounted to `/usr/src/habitrpg`
2. Host machine different from container OS

So in my experience my host machine is macOS, where my node packages are built for that OS. However the docker container will not work correctly when it tries run some of those node packages under linux, which it will because the entire `habitrpg` directly in the container is mapped to my local machine.

I’ve had to solve this by pointing the volumes to more specific directories that avoid the `node_modules` directory, but is very much a bandaid solution for myself:

```
  client:
    volumes:
      - './website/client:/usr/src/habitrpg/website/client'

  server:
    volumes:
      - './website/server:/usr/src/habitrpg/website/server'
```
