### ISSUE TITLE
CSS margin of headers and paragraphs renders poorly for Markdown

### ISSUE THREAD

**Issue by texastoland** [HabitRPG/habitica#10477]
### Description

1. Headers have 0 vertical spacing before. In my party wiki I work around it with horizontal rules.

2. Paragraphs have 0 vertical spacing before or after. I first noticed in a popular guild when someone asked how to format a long post. They worked around it with paragraphs consisting of a single `.`.

![habitica com_party](https://user-images.githubusercontent.com/48431/41887502-8e356f26-78c6-11e8-8bd8-a967fbcaf1ab.png)

### Proposal

I know CSS but I'm no designer.

1. Headers should have more spacing above than below. GitHub uses a ratio of 3:2. The existing `margin-bottow` could be split with `margin-top`.

    ```css
    h1 { /* _not_ scoped to Markdown  */
      margin-bottom: 10px; /* formerly `24px` */
      margin-top: 14px; /* still `24px` total */
    } /* ratio 2.8:2 */
    h2 {
      margin-bottom: 7px; /* formerly `16px` */
      margin-top: 9px; /* still `16px` total */
    } /* ratio 2.6:2 */
    h3 {
      margin-bottom: 4px; /* formerly `9px` */
      margin-top: 5px; /* still `9px` total */
    } /* ratio 2.5:2 */
    /* etc. */
    ```

2. Paragraphs in Markdown only need `margin-bottom` around `9px`.

    ```css
    .markdown p { /* `>` here would miss nested elements  */
      margin-bottom: 9px;
    }
    ```

![habitica com_party 1](https://user-images.githubusercontent.com/48431/41929755-b3a6ff54-793e-11e8-9ade-107cf9d7a4a5.png)

**Comment by citrusella** [comment]
I know that the spacing between paragraphs is well-known, since it's usually advised to use `&nbsp;` in between if you want to get the illusion of spacing.

i.e. this has `&nbsp;` after it  
&nbsp;  
and then a second paragraph after the `&nbsp;`

(I don't have any answers, I just wanted to note that, since it's common-ish advice)

**Comment by texastoland** [comment]
@citrusella the problem is that's a workaround to incorrect CSS rather than Markdown itself. I just uploaded a screenshot with fixes applied.

**Comment by texastoland** [comment]
@Alys low-hanging PR?

**Comment by Alys** [comment]
I think a change to markdown styles to add spacing after paragraphs would be a good enhancement (and would be consistent with how the Android app displays them), although we should keep in mind that when it goes live, all tasks, PMs, and chat posts that already use a workaround for spacing will now have too much spacing, so perhaps a Bailey message at the time would be a good idea so that we don't get too many "bug" reports.
I wouldn't be opposed to spacing changes for markdown styles for headings, but I don't think we should change the generic heading styles without careful consideration of how that would affect the rest of the site.

**Comment by texastoland** [comment]
> don't think we should change the generic heading styles without careful consideration of how that would affect the rest of the site.

That occurred to me too. I'd be amenable to enclosing it in `.markdown` just like `p`. I wanted to suggest a unified approach first.

**Comment by texastoland** [comment]
@Alys ping. The next bug I'd like to knock out is missing emoji images.

**Comment by texastoland** [comment]
Is there a blocker? I'm interested in other tasks but I won't start until I can push an easy one through. CC @Alys

**Comment by Alys** [comment]
@texastoland I think the only blocker is that the staff have had many PRs to review lately and are handling them in priority order. I'm sure they'll look at this one as soon as they can!

**Comment by paglias** [comment]
@Tressley what do you think?

**Comment by Tressley** [comment]
I think this is a great suggestion. My only feedback is to change 9px to 8px to align with our 4px grid.

```css
h3 {
  margin-bottom: 4px; /* formerly `9px` */
  margin-top: 4px; /* still `9px` total */
} /* ratio 2.5:2 */
/* etc. */
```

```css
.markdown p { /* `>` here would miss nested elements  */
  margin-bottom: 8px;
}
```
