### ISSUE TITLE
API inconsistency: "Delete a group" / "Delete a group message"?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3679]
In the [API documentation](https://habitrpg.com/static/api), in the groups section, there's something odd about the only "Delete" option (see screenshot below). It's labelled "Delete a group" (which seems a little extreme for an API call) but its URL path includes a message ID implying that it's for deleting a message, however there's no field to include the message ID.

This is the code from src/routes/apiv2.coffee:

```
"/groups/{gid}/chat/{messageId}":
  spec:
    method: 'DELETE'
    description: 'Delete a group'
    parameters: [path('gid','ID of group to delete','string')]
  middleware: [auth.auth, i18n.getUserLanguage, groups.attachGroup]
  action: groups.deleteChatMessage
```

EDIT:
If you use the API through your own script, not through the API docs page, with a URL like /groups/{gid}/chat/{messageId}, then it DOES delete the chat message. Yay. :)

When I get my VM working again, I'll try to do a PR for this, unless someone gets in first (please feel free to do so if you wish, gentle reader).

![screen shot 2014-07-03 at 5 41 46 pm](https://cloud.githubusercontent.com/assets/1495809/3466735/e59ec69c-0285-11e4-8438-752b28ff07a4.png)
