### ISSUE TITLE
Flying Pig soars too high, must have its glory contained

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9364]
When you tame a flying pig pet, the greyed out version hovers about a half-centimeter too high, so that they're actually flying out of the top of the box. This should be adjusted.

<img width="615" alt="screen shot 2017-11-01 at 6 16 25 pm" src="https://user-images.githubusercontent.com/3494081/32305157-068c5138-bf31-11e7-9c7e-5b1d533c01da.png">

**Comment by kipraske** [comment]
I have a fix for this, but I am going to do some additional testing to make sure I didn't mess up any of the other pets. In particular I am not sure at this point why flying pigs need this special treatment anyway.

Anyway the problem is that we have this CSS

``` css
  .stable .item .item-content.Pet:not(.FlyingPig) {
    top: -28px;
  }

  .stable .item .item-content.FlyingPig {
    top: 7px;
  }
```

But we remove the `.FlyingPig` class from the pig when it is greyed out for some reason. My fix adds this to the greyed out version, but this also will add a class to every other pet as well (the missing class is `${pet.eggKey}`). So I want to test each of the 9 pets for any side effects.

I'll make that PR later today.
